export interface Question {
    id: string;
    question: string;
    options: string[];
    conditional?: (answers: Record<string, any>) => boolean;
    allowCustom?: boolean;
  }
  
  // Questions based on career stage
  export const questions = {
    "Pathfinder": [
      {
        id: 'educationLevel',
        question: 'What level of education are you at?',
        options: ['High School', 'Some College', 'Associate Degree', 'Bachelor\'s Degree', 'Master\'s Degree', 'PhD']
      },
      {
        id: 'program',
        question: 'What program was/is offered?',
        options: ["Other (please specify)","Accounting", "Actuarial Science", "Advertising", "Aerospace Engineering", "Anesthesiology", "Animation", "Applied Mathematics", "Applied Physics", "Architectural Engineering", "Architecture", "Artificial Intelligence", "Astronautical Engineering", "Astronomy", "Astrophysics", "Atmospheric Science", "Atmospheric Sciences", "Audio Technology", "Automotive Engineering", "Avionics Engineering", "Biochemical Engineering", "Biochemistry", "Biology", "Biomechanical Engineering",
    "Biomedical Engineering", "Biomedical Science", "Biotechnology", "Business Administration", "Business Analytics", "Business Technology", "Chemical Engineering", "Chemistry", "Chiropractic Medicine", "Cinematography", "Civil Engineering", "Climate Policy", "Climate Science", "Clinical Psychology", "Cognitive Science", "Communications", "Computational Astrophysics", "Computer Engineering", "Computer Graphics", "Computer Science", "Computer Science with Robotics focus", "Conservation Biology", "Construction Engineering", "Corporate Sustainability", "Counseling",
    "Criminal Justice", "Cryptography", "Curriculum and Instruction", "Cybersecurity", "Data Engineering", "Data Science", "Dentistry", "Dietetics", "Digital Arts", "Digital Media", "Directing", "Earth Science", "Ecological Engineering", "Ecology", "Economics", "Education", "Education Administration", "Education Policy", "Educational Leadership", "Educational Technology", "Electrical Engineering", "Engineering Geology", "Engineering Management", "Engineering Physics", "English", "Entrepreneurship", "Environmental Design", "Environmental Engineering", "Environmental Geology", "Environmental Science", "Event Management", "Fashion Design", "Fashion Merchandising", "Fashion Technology", "Film Production", "Film Studies", "Finance", "Financial Technology",
    "Fine Arts", "Forensic Science", "Game Development", "Geological Engineering", "Geology", "Geophysics",
    "Geosciences", "Geotechnical Engineering", "Graphic Design", "Healthcare Administration", "Hospitality Management", "Human Resources",
    "Human-Computer Interaction", "Immunology", "Industrial Engineering", "Information Assurance", "Information Science", "Information Security",
    "Information Systems", "Information Technology", "Innovation Management", "Instructional Design", "Interactive Media",
    "Interior Architecture", "Interior Design", "Journalism", "Library Science", "Linguistics", "Logistics Management", "Machine Learning", "Management", "Management Information Systems", "Manufacturing Engineering", "Marine Biology", "Marine Engineering", "Marketing", "Materials Engineering", "Materials Science", "Mathematics", "Mechanical Engineering", "Mechanical Engineering with Nuclear focus", "Mechanical Engineering with Petroleum focus", "Mechatronics", "Media Arts", "Media Studies", "Medical Engineering", "Medical Laboratory Science", "Medical Microbiology", "Medicine", "Metallurgical Engineering", "Meteorology", "Microbiology", "Molecular Biology", "Molecular Genetics", "Music Business", "Music Production", "Naval Architecture", "Network Engineering", "Network Security", "Nuclear Engineering", "Nursing", "Nutrition",
    "Occupational Therapy", "Ocean Engineering", "Oceanography", "Operations Management", "Optometry", "Pediatrics", "Petroleum Engineering", "Pharmacy", "Photography", "Physical Therapy", "Physics", "Process Engineering", "Project Management", "Psychology", "Public Health", "Public Policy", "Public Relations", "Radiological Science", "Radiology", "Risk Management",
    "Robotics Engineering", "Software Architecture", "Software Engineering", "Sound Engineering", "Space Science", "Special Education", "Statistics", "Structural Engineering", "Subject-Specific Degree", "Supply Chain Management", "Surgery", "Sustainability Management", "Systems Engineering", "Taxation", "Technical Communication", "Textile Design", "Visual Arts", "Visual Communications", "Web Development", ],
        conditional: (answers: Record<string, any>) => {
          const educationLevel = answers.educationLevel;
          return educationLevel && !['High School', 'Some College'].includes(educationLevel);
        }
      },
      {
        id: 'currentSkills',
        question: 'What skills do you have?',
        options: ["2D/3D Animation", "3D Modeling", "Accounting", "Actor Direction", "Adaptive Teaching", "Administration", "Adobe Creative Suite", "Aerodynamics", "Agile Methodologies", "AI Fine-tuning", "AI Systems Knowledge", "Algorithms", "Anatomy", "Android Development", "Anesthesia Administration", "API Design", "API Development", "Astrophysical Research", "Atmospheric Physics", "Audio Editing", "Audio Mixing", "Auditing", "AutoCAD", "Automation", "Automotive Systems", "Avionics", "AWS", "Azure", "Backend Development", "Backup & Recovery", "Behavioral Management", "Big Data", "Big Data Tools (Spark, Hadoop)", "Bioinformatics", "Biomaterials", "Biomechanics", "Blockchain", "Brand Communication", "Brand Development", "Brand Messaging", "Budgeting", "Bug Tracking", "Building Codes and Standards", "Building Design", "Business Planning", "Business Process Modeling", "C#", "C#/C++ Programming", "CAD Design", "CAD/CAM Systems", "Carbon Footprint Analysis", "Career Guidance", "Cataloging", "Chain of Custody", "Character Design", "Chemical Analysis", "Chemical Reactions", "Child Healthcare", "CI/CD", "Cinematography", "Circuit Design", "Circular Economy Strategies", "Classroom Management", "Client Communication", "Client Management", "Client Relations", "Climate Modeling", "Clinical Evaluation", "Cloud Computing", "Color Theory", "Communication", "Communication and Presentation", "Compliance", "Computational Fluid Dynamics (CFD)", "Computational Modeling", "Computer Vision", "Computer-Aided Design (CAD)", "Conceptual Thinking", "Content Creation", "Content Writing", "Control Systems", "Counseling", "Courtroom Testimony", "Creative Direction", "Creative Strategy", "Creative Writing", "Creativity", "Credit Risk Assessment", "Crime Scene Analysis", "Crisis Management", "Critical Thinking", "CRM Management", "Cross-Browser Compatibility", "Cross-Functional Collaboration", "Cryptography", "Cultural Sensitivity", "Curriculum Design", "Curriculum Development", "Customer Relations", "Data Analysis", "Data Annotation", "Data Interpretation", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization", "Data-Driven Decision Making", "Database Management", "DAW Proficiency", "Debugging", "Decision Making", "Deep Learning", "Dental Procedures", "Diagnosis", "Dietary Counseling", "Digital Design Tools", "DNA Analysis", "Drilling Techniques", "E-Learning Development", "Editing", "Educational Research", "Electric Vehicle Technology", "Electronics", "Emergency Alert Systems", "Employee Relations", "Energy Production",
           "Enhanced Oil Recovery", "Environmental Data Analysis", "Environmental Impact Assessment", "Environmental Modeling", "Environmental Policy", "ERP System Proficiency", "Ethical Hacking", "Event Coordination", "Evidence Interpretation", "Excel", "Experimental Design", "Eye Exams", "Failure Analysis", "Fashion Illustration", "Feature Engineering", "Field Research Techniques", "Field Sampling", "Fieldwork", "Financial Analysis", "Financial Management", "Financial Modeling", "Financial Planning", "Financial Reporting", "Firewall Management", "Fluid Dynamics", "Forecasting", "Foundation Design", "Frontend Development", "Game Design", "Garment Construction", "Genetics", "Geological and Site Investigation", "Geological Surveys", "Geology", "Geospatial Analysis", "GIS Mapping", "Health Education", "Healthcare Management", "HR Policies", "HTML/CSS", "Human Factors Engineering", "Human-AI Interaction Design", "Incident Response", "Individualized Education Plans (IEPs)", "Information Management", "Innovation", "Instructional Strategies", "Instructional Technology", "Instrumentation", "Inventory Control", "Investment Management", "Investment Strategies", "iOS Development", "IT Infrastructure", "JavaScript", "Laboratory Techniques", "Laboratory Testing", "Language Instruction", "Leadership", "Lean Manufacturing", "Lesson Planning", "Lighting Design", "Lighting Techniques", "Load Calculations", "Load Testing", "Loan Evaluation", "Logistics Management", "Machine Learning", "Machine Learning Concepts", "Manufacturing Processes", "Marine Systems Integration", "Market Analysis", "Market Research", "Marketing Strategy", "Material Science", "Material Selection", "Materials Science", "Materials Testing", "Mathematical Modeling", "Mechanical Design", "Mechanical Systems", "Media Relations", "Medical Device Design", "Medical Imaging", "Medical Knowledge", "Medication Management", "Mental Health Support", "Mergers & Acquisitions", "Microbial Analysis", "Model Deployment", "Model Evaluation", "Model-Based Systems Engineering (MBSE)", "Molecular Biology", "Music Composition", "Natural Language Processing", "Network Configuration", "Network Security", "Neural Networks", "Node.js", "NoSQL Databases", "Nuclear Physics", "Nuclear Reactor Design", "Nutrition Planning", "Observational Techniques", "Operations Research", "Pain Management", "Pathogen Identification", "Patient Care", "Patient Counseling", "Patient Monitoring", "Pattern Making", "Penetration Testing", "Performance Optimization", "Performance Tuning", "Pharmaceutical Knowledge", "Photo Editing", "Photography", "Policy Analysis", "Policy Evaluation",
            "Policy Implementation", "Pollution Control", "Post-Production", "Power Systems", "Powertrain Engineering", "Presentation Skills", "Problem Solving", "Process Control", "Process Design", "Process Improvement", "Process Optimization", "Product Development", "Product Roadmapping", "Production Management", "Programming", "Project Management", "Project Planning", "Prompt Engineering", "Propulsion Systems", "Prototyping", "Psychological Assessment", "Public Communication", "Python", "Python/R Programming", "Quality Control", "Radiation Safety", "React", "React Native", "Reactor Design", "Recruitment", "Regression Testing", "Regulatory Compliance", "Rehabilitation", "Remediation Technologies", "Report Writing", "Requirements Engineering", "Requirements Gathering", "Research", "Research Assistance", "Research Methodologies", "Research Methodology", "Research Skills", "Reservoir Engineering", "Responsive Design", "Risk Analysis", "Risk Assessment", "Risk Management", "Roadmapping", "Robotics Design", "Rock Mechanics", "Safety Protocols", "Sales Strategy", "Scientific Computing", "Scientific Writing", "Script Analysis", "Scripting and Automation", "Security", "Security Best Practices", "Security Frameworks", "Seismic Design", "Seismic Risk Assessment", "SEO Knowledge", "Server Administration", "Server Management", "Ship Design", "Signal Processing", "Slope Stability Analysis", "Smart Contracts", "Social Engineering Techniques", "Software Architecture", "Soil and Rock Mechanics", "Sound Design", "Space Planning", "Spatial Computing", "Spinal Adjustment", "SQL", "Stakeholder Communication", "Stakeholder Engagement", "Stakeholder Management", "Statistical Analysis", "Statistical Modeling", "Statistics", "Storyboarding", "Storytelling", "Strategic Planning", "Stress Analysis", "Structural Analysis", "Structural Design", "Supplier Relations", "Supply Chain Coordination", "Supply Chain Management", "Surgical Techniques", "Sustainability", "Sustainability Reporting", "Systems Design", "Systems Integration", "Tax Compliance", "Tax Planning", "Teacher Training", "Teaching", "Team Leadership", "Technical Analysis", "Technical Documentation", "Telescope Operation", "Test Automation Frameworks", "Testing", "Testing and Debugging", "Textile Design", "Theoretical Physics", "Therapeutic Techniques", "Therapy", "Thermodynamics", "Tissue Engineering", "Transportation Management", "Trend Analysis", "Troubleshooting", "Typography", "UI/UX Design Principles", "Unit Testing", "Unity", "Unity/Unreal Engine", "User Experience Design", "User Research", "UX Design for VR/AR",
             "Vehicle Design", "Vendor Management", "Version Control", "Version Control (Git)", "Video Editing", "Vision Correction", "Visual Communication", "Visual Composition", "Visual Design", "Visual Storytelling", "VPN Setup", "Vulnerability Assessment", "Waste Management", "Water Treatment", "Weather Forecasting", "Well Design", "Wireframing", "Other"]
      },
      {
        id: 'interestedSkills',
        question: 'What skills intrigue you and you are interested in learning?',
        options: ["2D/3D Animation", "3D Modeling", "Accounting", "Actor Direction", "Adaptive Teaching", "Administration", "Adobe Creative Suite", "Aerodynamics", "Agile Methodologies", "AI Fine-tuning", "AI Systems Knowledge", "Algorithms", "Anatomy", "Android Development", "Anesthesia Administration", "API Design", "API Development", "Astrophysical Research", "Atmospheric Physics", "Audio Editing", "Audio Mixing", "Auditing", "AutoCAD", "Automation", "Automotive Systems", "Avionics", "AWS", "Azure", "Backend Development", "Backup & Recovery", "Behavioral Management", "Big Data", "Big Data Tools (Spark, Hadoop)", "Bioinformatics", "Biomaterials", "Biomechanics", "Blockchain", "Brand Communication", "Brand Development", "Brand Messaging", "Budgeting", "Bug Tracking", "Building Codes and Standards", "Building Design", "Business Planning", "Business Process Modeling", "C#", "C#/C++ Programming", "CAD Design", "CAD/CAM Systems", "Carbon Footprint Analysis", "Career Guidance", "Cataloging", "Chain of Custody", "Character Design", "Chemical Analysis", "Chemical Reactions", "Child Healthcare", "CI/CD", "Cinematography", "Circuit Design", "Circular Economy Strategies", "Classroom Management", "Client Communication", "Client Management", "Client Relations", "Climate Modeling", "Clinical Evaluation", "Cloud Computing", "Color Theory", "Communication", "Communication and Presentation", "Compliance", "Computational Fluid Dynamics (CFD)", "Computational Modeling", "Computer Vision", "Computer-Aided Design (CAD)", "Conceptual Thinking", "Content Creation", "Content Writing", "Control Systems", "Counseling", "Courtroom Testimony", "Creative Direction", "Creative Strategy", "Creative Writing", "Creativity", "Credit Risk Assessment", "Crime Scene Analysis", "Crisis Management", "Critical Thinking", "CRM Management", "Cross-Browser Compatibility", "Cross-Functional Collaboration", "Cryptography", "Cultural Sensitivity", "Curriculum Design", "Curriculum Development", "Customer Relations", "Data Analysis", "Data Annotation", "Data Interpretation", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization", "Data-Driven Decision Making", "Database Management", "DAW Proficiency", "Debugging", "Decision Making", "Deep Learning", "Dental Procedures", "Diagnosis", "Dietary Counseling", "Digital Design Tools", "DNA Analysis", "Drilling Techniques", "E-Learning Development", "Editing", "Educational Research", "Electric Vehicle Technology", "Electronics", "Emergency Alert Systems", "Employee Relations", "Energy Production",
           "Enhanced Oil Recovery", "Environmental Data Analysis", "Environmental Impact Assessment", "Environmental Modeling", "Environmental Policy", "ERP System Proficiency", "Ethical Hacking", "Event Coordination", "Evidence Interpretation", "Excel", "Experimental Design", "Eye Exams", "Failure Analysis", "Fashion Illustration", "Feature Engineering", "Field Research Techniques", "Field Sampling", "Fieldwork", "Financial Analysis", "Financial Management", "Financial Modeling", "Financial Planning", "Financial Reporting", "Firewall Management", "Fluid Dynamics", "Forecasting", "Foundation Design", "Frontend Development", "Game Design", "Garment Construction", "Genetics", "Geological and Site Investigation", "Geological Surveys", "Geology", "Geospatial Analysis", "GIS Mapping", "Health Education", "Healthcare Management", "HR Policies", "HTML/CSS", "Human Factors Engineering", "Human-AI Interaction Design", "Incident Response", "Individualized Education Plans (IEPs)", "Information Management", "Innovation", "Instructional Strategies", "Instructional Technology", "Instrumentation", "Inventory Control", "Investment Management", "Investment Strategies", "iOS Development", "IT Infrastructure", "JavaScript", "Laboratory Techniques", "Laboratory Testing", "Language Instruction", "Leadership", "Lean Manufacturing", "Lesson Planning", "Lighting Design", "Lighting Techniques", "Load Calculations", "Load Testing", "Loan Evaluation", "Logistics Management", "Machine Learning", "Machine Learning Concepts", "Manufacturing Processes", "Marine Systems Integration", "Market Analysis", "Market Research", "Marketing Strategy", "Material Science", "Material Selection", "Materials Science", "Materials Testing", "Mathematical Modeling", "Mechanical Design", "Mechanical Systems", "Media Relations", "Medical Device Design", "Medical Imaging", "Medical Knowledge", "Medication Management", "Mental Health Support", "Mergers & Acquisitions", "Microbial Analysis", "Model Deployment", "Model Evaluation", "Model-Based Systems Engineering (MBSE)", "Molecular Biology", "Music Composition", "Natural Language Processing", "Network Configuration", "Network Security", "Neural Networks", "Node.js", "NoSQL Databases", "Nuclear Physics", "Nuclear Reactor Design", "Nutrition Planning", "Observational Techniques", "Operations Research", "Pain Management", "Pathogen Identification", "Patient Care", "Patient Counseling", "Patient Monitoring", "Pattern Making", "Penetration Testing", "Performance Optimization", "Performance Tuning", "Pharmaceutical Knowledge", "Photo Editing", "Photography", "Policy Analysis", "Policy Evaluation",
            "Policy Implementation", "Pollution Control", "Post-Production", "Power Systems", "Powertrain Engineering", "Presentation Skills", "Problem Solving", "Process Control", "Process Design", "Process Improvement", "Process Optimization", "Product Development", "Product Roadmapping", "Production Management", "Programming", "Project Management", "Project Planning", "Prompt Engineering", "Propulsion Systems", "Prototyping", "Psychological Assessment", "Public Communication", "Python", "Python/R Programming", "Quality Control", "Radiation Safety", "React", "React Native", "Reactor Design", "Recruitment", "Regression Testing", "Regulatory Compliance", "Rehabilitation", "Remediation Technologies", "Report Writing", "Requirements Engineering", "Requirements Gathering", "Research", "Research Assistance", "Research Methodologies", "Research Methodology", "Research Skills", "Reservoir Engineering", "Responsive Design", "Risk Analysis", "Risk Assessment", "Risk Management", "Roadmapping", "Robotics Design", "Rock Mechanics", "Safety Protocols", "Sales Strategy", "Scientific Computing", "Scientific Writing", "Script Analysis", "Scripting and Automation", "Security", "Security Best Practices", "Security Frameworks", "Seismic Design", "Seismic Risk Assessment", "SEO Knowledge", "Server Administration", "Server Management", "Ship Design", "Signal Processing", "Slope Stability Analysis", "Smart Contracts", "Social Engineering Techniques", "Software Architecture", "Soil and Rock Mechanics", "Sound Design", "Space Planning", "Spatial Computing", "Spinal Adjustment", "SQL", "Stakeholder Communication", "Stakeholder Engagement", "Stakeholder Management", "Statistical Analysis", "Statistical Modeling", "Statistics", "Storyboarding", "Storytelling", "Strategic Planning", "Stress Analysis", "Structural Analysis", "Structural Design", "Supplier Relations", "Supply Chain Coordination", "Supply Chain Management", "Surgical Techniques", "Sustainability", "Sustainability Reporting", "Systems Design", "Systems Integration", "Tax Compliance", "Tax Planning", "Teacher Training", "Teaching", "Team Leadership", "Technical Analysis", "Technical Documentation", "Telescope Operation", "Test Automation Frameworks", "Testing", "Testing and Debugging", "Textile Design", "Theoretical Physics", "Therapeutic Techniques", "Therapy", "Thermodynamics", "Tissue Engineering", "Transportation Management", "Trend Analysis", "Troubleshooting", "Typography", "UI/UX Design Principles", "Unit Testing", "Unity", "Unity/Unreal Engine", "User Experience Design", "User Research", "UX Design for VR/AR",
             "Vehicle Design", "Vendor Management", "Version Control", "Version Control (Git)", "Video Editing", "Vision Correction", "Visual Communication", "Visual Composition", "Visual Design", "Visual Storytelling", "VPN Setup", "Vulnerability Assessment", "Waste Management", "Water Treatment", "Weather Forecasting", "Well Design", "Wireframing", "Other"]
      },
      {
        id: 'mainInterests',
        question: 'What are your main interests?',
        options: ["3D Graphics", "Accounting", "AI", "Animation", "App Development", "Architecture", "Art", "Artificial Intelligence", "Astronomy", "Attention to Detail", "Augmented Reality", "Automated Systems", "Automotive", "Aviation", "Banking", "Biology", "Biotechnology", "Blockchain", "Brand Development", "Building Scalable Systems", "Business", "Business Analysis", "Business Development", "Business Innovation", "Business Intelligence", "Business Operations", "Business Strategy", "Chemistry", "Civil Engineering", "Climate", "Climate Action", "Climate Change", "Cloud Databases", "Cloud Infrastructure", "Coding", "Cognitive Science", "Collaboration", "Collaborative Work", "Communication", "Conservation", "Construction", "Consumer Behavior", "Consumer Trends", "Content Creation", "Continuous Learning", "Corporate Responsibility", "Cosmology", "Creative Writing", "Creativity", "Criminal Justice", "Cross-Functional Leadership", "Cultural Exchange", "Cultural Movements", "Cultural Trends", "Current Events", "Cybersecurity", "Data", "Data Analysis", "Data Analytics", "Data Architecture", "Data Visualization", "Data-Driven Decision Making", "Dentistry", "Design", "Digital Art", "Digital Forensics", "Earth Science", "Earth Systems", "Economics", "Education", "Efficiency", "Electricity",
          "Emerging Technologies", "Energy", "Engineering", "Enterprise Systems", "Entrepreneurship", "Environmental Conservation", "Environmental Impact", "Environmental Issues", "Environmental Protection", "Environmental Science", "Environmental Sustainability", "Ethical Hacking", "Event Management", "Experimentation", "Fashion", "Field Operations", "Film", "Finance", "Forensics", "Game Development", "Gaming", "Geology", "Global Trade", "Green Technology", "Healthcare", "Home Furnishings", "Hospitality", "Human Behavior", "Human Physiology", "Human-Computer Interaction", "Immersive Technology", "Industry Trends", "Infectious Diseases", "Information Technology", "Infrastructure", "Infrastructure Design", "Innovation", "Innovation in AI", "Insurance", "Investments", "IT Consultancy", "Laboratory Work", "Language", "Language Models", "Leadership", "Legal Processes", "Management", "Manufacturing", "Maritime Technology", "Marketing", "Marketing Strategy", "Material Science", "Materials Science", "Mathematics", "Mechanical Systems", "Mechatronics", "Medical Research", "Medicine", "Mental Health", "Mentorship", "Meteorology", "Microbiology", "Mobile Apps", "Music", "Natural Resources", "Nature", "Naval Innovation", "Negotiation", "Networking", "New Materials", "Nuclear Science", "Numbers", "Nutrition", "Operations", "Organization", "Organizational Behavior", "Organizational Development", "Outdoor Work", "Pediatrics", "People Skills", "Physical Therapy", "Physics", "Policy", "Popular Culture", "Power Generation",
          "Predictive Analytics", "Privacy Protection", "Problem Solving", "Process Improvement", "Product Innovation", "Psychology", "Public Health", "Public Policy", "Public Relations", "Public Safety", "Quality Assurance", "Rehabilitation", "Renewable Energy", "Research", "Research and Development", "Risk Management", "Robotics", "Safety Systems", "Sales", "Science", "Software Development", "Software Quality Advocacy", "Sound Engineering", "Space", "Space Exploration", "Special Needs", "Startups", "Statistics", "Storytelling", "Surgery", "Sustainability", "Sustainable Building", "Sustainable Extraction", "Systems Optimization", "Systems Thinking", "Taxation", "Teaching", "Team Collaboration", "Technology", "Technology Implementation", "Technology Management", "Textiles", "Transportation", "User Experience", "User-Centered Testing", "User-Centric Design", "User-Centric Innovation", "Virtual Reality", "Vision Care", "Visual Arts", "Visual Culture", "Visual Storytelling", "Wealth Management", "Wellness", "Writing", "Other"]
      },
      {
        id: 'interestedFields',
        question: 'What fields are you interested in?',
        options: ["Technology", "Business", "Healthcare", "Finance", "Creative Arts",
    "Engineering", "Science", "Education", "Environment", 'Other']
      },
      {
        id: 'workEnvironment',
        question: 'What kind of work environment would you be interested in?',
        options: ['Remote', 'Office-based', 'Hybrid (Office-based + Remote)', 'Outdoor', 'Laboratory', 'Hospital/Clinical', 'Startup', 'Large Corporation']
      }
    ],
    "Trailblazer": [
      {
        id: 'currentPath',
        question: 'What career path are you in?',
        options: ["Accountant", "Actuary", "Aerospace Engineer", "AI Engineer", "AI Product Manager", "Anesthesiologist", "Animator", "Art Director", "Astronomer", "Auditor", "Automotive Engineer", "Backend Developer", "Biologist", "Biomedical Engineer", "Biotechnologist", "Blockchain Developer", "Business Analyst", "Chemical Engineer", "Chemist", "Chiropractor", "Civil Engineer", "Climate Scientist", 
    "Cloud Architect", "College Professor", "Copywriter", "Creative Director", "Credit Analyst", "Curriculum Developer", "Cybersecurity Analyst", "Data Analyst", "Data Engineer", "Data Scientist", "Database Administrator", "Dentist", "DevOps Engineer", "Dietitian", "Education Policy Analyst", "Educational Consultant", "Electrical Engineer", "Entrepreneur", "Environmental Engineer", "Environmental Scientist", "ESL Teacher", "Ethical Hacker", "Event Planner", "Fashion Designer", "Film Director", "Financial Analyst", "Financial Planner", "Forensic Scientist", "Frontend Developer", "Full-Stack Developer", "Game Developer", "Geologist", "Geotechnical Engineer", "Graphic Designer", "Healthcare Administrator", "Human Resources Manager", "Industrial Engineer", "Instructional Designer", "Insurance Underwriter", "Interior Designer", "Investment Banker", "IT Manager", "Librarian", "Logistics Manager", "Machine Learning Engineer", "Management Consultant", "Marine Engineer", "Materials Engineer", "Mechanical Engineer", "Medical Laboratory Scientist", "Medical Researcher", "Meteorologist", "Microbiologist", "Mobile App Developer", "Music Producer", "Network Administrator", "Nuclear Engineer", "Nurse Practitioner", "Occupational Therapist", "Operations Manager", "Optometrist", "Pediatrician", "Petroleum Engineer", "Pharmacist", "Photographer", "Physical Therapist", "Physicist", "Product Manager", "Project Manager", "Prompt Engineer", "Psychologist", "Public Relations Manager", "QA Engineer", "Radiologist", "Risk Manager", 
    "Robotics Engineer", "Sales Manager", "School Counselor", "School Principal", "Software Engineer", "Special Education Teacher", "Structural Engineer", "Supply Chain Manager", "Surgeon", "Sustainability Specialist", "Systems Analyst", "Systems Engineer", "Tax Consultant", "Teacher", "Technical Writer", "UX Designer", "Video Editor", "VR/AR Developer", "Wealth Manager", "Other"]
      },
      {
        id: 'yearsExperience',
        question: 'How many years of experience do you have in that path?',
        options: ['0-1 years', '2-3 years', '4-5 years', '6-10 years', '10+ years']
      },
      {
        id: 'seniorityLevel',
        question: 'What is your seniority level?',
        options: ['Entry Level', 'Junior', 'Mid-level', 'Senior', 'Lead/Manager', 'Director', 'Executive']
      },
      {
        id: 'educationLevel',
        question: 'What level of education have you attained?',
        options: ['High School', 'Some College', 'Associate Degree', 'Bachelor\'s Degree', 'Master\'s Degree', 'PhD']
      },
      {
        id: 'program',
        question: 'What program?',
        options: ["Other (please specify)","Accounting", "Actuarial Science", "Advertising", "Aerospace Engineering", "Anesthesiology", "Animation", "Applied Mathematics", "Applied Physics", "Architectural Engineering", "Architecture", "Artificial Intelligence", "Astronautical Engineering", "Astronomy", "Astrophysics", "Atmospheric Science", "Atmospheric Sciences", "Audio Technology", "Automotive Engineering", "Avionics Engineering", "Biochemical Engineering", "Biochemistry", "Biology", "Biomechanical Engineering",
    "Biomedical Engineering", "Biomedical Science", "Biotechnology", "Business Administration", "Business Analytics", "Business Technology", "Chemical Engineering", "Chemistry", "Chiropractic Medicine", "Cinematography", "Civil Engineering", "Climate Policy", "Climate Science", "Clinical Psychology", "Cognitive Science", "Communications", "Computational Astrophysics", "Computer Engineering", "Computer Graphics", "Computer Science", "Computer Science with Robotics focus", "Conservation Biology", "Construction Engineering", "Corporate Sustainability", "Counseling",
    "Criminal Justice", "Cryptography", "Curriculum and Instruction", "Cybersecurity", "Data Engineering", "Data Science", "Dentistry", "Dietetics", "Digital Arts", "Digital Media", "Directing", "Earth Science", "Ecological Engineering", "Ecology", "Economics", "Education", "Education Administration", "Education Policy", "Educational Leadership", "Educational Technology", "Electrical Engineering", "Engineering Geology", "Engineering Management", "Engineering Physics", "English", "Entrepreneurship", "Environmental Design", "Environmental Engineering", "Environmental Geology", "Environmental Science", "Event Management", "Fashion Design", "Fashion Merchandising", "Fashion Technology", "Film Production", "Film Studies", "Finance", "Financial Technology",
    "Fine Arts", "Forensic Science", "Game Development", "Geological Engineering", "Geology", "Geophysics",
    "Geosciences", "Geotechnical Engineering", "Graphic Design", "Healthcare Administration", "Hospitality Management", "Human Resources",
    "Human-Computer Interaction", "Immunology", "Industrial Engineering", "Information Assurance", "Information Science", "Information Security",
    "Information Systems", "Information Technology", "Innovation Management", "Instructional Design", "Interactive Media",
    "Interior Architecture", "Interior Design", "Journalism", "Library Science", "Linguistics", "Logistics Management", "Machine Learning", "Management", "Management Information Systems", "Manufacturing Engineering", "Marine Biology", "Marine Engineering", "Marketing", "Materials Engineering", "Materials Science", "Mathematics", "Mechanical Engineering", "Mechanical Engineering with Nuclear focus", "Mechanical Engineering with Petroleum focus", "Mechatronics", "Media Arts", "Media Studies", "Medical Engineering", "Medical Laboratory Science", "Medical Microbiology", "Medicine", "Metallurgical Engineering", "Meteorology", "Microbiology", "Molecular Biology", "Molecular Genetics", "Music Business", "Music Production", "Naval Architecture", "Network Engineering", "Network Security", "Nuclear Engineering", "Nursing", "Nutrition",
    "Occupational Therapy", "Ocean Engineering", "Oceanography", "Operations Management", "Optometry", "Pediatrics", "Petroleum Engineering", "Pharmacy", "Photography", "Physical Therapy", "Physics", "Process Engineering", "Project Management", "Psychology", "Public Health", "Public Policy", "Public Relations", "Radiological Science", "Radiology", "Risk Management",
    "Robotics Engineering", "Software Architecture", "Software Engineering", "Sound Engineering", "Space Science", "Special Education", "Statistics", "Structural Engineering", "Subject-Specific Degree", "Supply Chain Management", "Surgery", "Sustainability Management", "Systems Engineering", "Taxation", "Technical Communication", "Textile Design", "Visual Arts", "Visual Communications", "Web Development"],
        conditional: (answers: Record<string, any>) => {
          const educationLevel = answers.educationLevel;
          return educationLevel && !['High School', 'Some College'].includes(educationLevel);
        }
      },
      {
        id: 'currentSkills',
        question: 'What skills do you possess at the moment?',
        options: ["2D/3D Animation", "3D Modeling", "Accounting", "Actor Direction", "Adaptive Teaching", "Administration", "Adobe Creative Suite", "Aerodynamics", "Agile Methodologies", "AI Fine-tuning", "AI Systems Knowledge", "Algorithms", "Anatomy", "Android Development", "Anesthesia Administration", "API Design", "API Development", "Astrophysical Research", "Atmospheric Physics", "Audio Editing", "Audio Mixing", "Auditing", "AutoCAD", "Automation", "Automotive Systems", "Avionics", "AWS", "Azure", "Backend Development", "Backup & Recovery", "Behavioral Management", "Big Data", "Big Data Tools (Spark, Hadoop)", "Bioinformatics", "Biomaterials", "Biomechanics", "Blockchain", "Brand Communication", "Brand Development", "Brand Messaging", "Budgeting", "Bug Tracking", "Building Codes and Standards", "Building Design", "Business Planning", "Business Process Modeling", "C#", "C#/C++ Programming", "CAD Design", "CAD/CAM Systems", "Carbon Footprint Analysis", "Career Guidance", "Cataloging", "Chain of Custody", "Character Design", "Chemical Analysis", "Chemical Reactions", "Child Healthcare", "CI/CD", "Cinematography", "Circuit Design", "Circular Economy Strategies", "Classroom Management", "Client Communication", "Client Management", "Client Relations", "Climate Modeling", "Clinical Evaluation", "Cloud Computing", "Color Theory", "Communication", "Communication and Presentation", "Compliance", "Computational Fluid Dynamics (CFD)", "Computational Modeling", "Computer Vision", "Computer-Aided Design (CAD)", "Conceptual Thinking", "Content Creation", "Content Writing", "Control Systems", "Counseling", "Courtroom Testimony", "Creative Direction", "Creative Strategy", "Creative Writing", "Creativity", "Credit Risk Assessment", "Crime Scene Analysis", "Crisis Management", "Critical Thinking", "CRM Management", "Cross-Browser Compatibility", "Cross-Functional Collaboration", "Cryptography", "Cultural Sensitivity", "Curriculum Design", "Curriculum Development", "Customer Relations", "Data Analysis", "Data Annotation", "Data Interpretation", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization", "Data-Driven Decision Making", "Database Management", "DAW Proficiency", "Debugging", "Decision Making", "Deep Learning", "Dental Procedures", "Diagnosis", "Dietary Counseling", "Digital Design Tools", "DNA Analysis", "Drilling Techniques", "E-Learning Development", "Editing", "Educational Research", "Electric Vehicle Technology", "Electronics", "Emergency Alert Systems", "Employee Relations", "Energy Production",
           "Enhanced Oil Recovery", "Environmental Data Analysis", "Environmental Impact Assessment", "Environmental Modeling", "Environmental Policy", "ERP System Proficiency", "Ethical Hacking", "Event Coordination", "Evidence Interpretation", "Excel", "Experimental Design", "Eye Exams", "Failure Analysis", "Fashion Illustration", "Feature Engineering", "Field Research Techniques", "Field Sampling", "Fieldwork", "Financial Analysis", "Financial Management", "Financial Modeling", "Financial Planning", "Financial Reporting", "Firewall Management", "Fluid Dynamics", "Forecasting", "Foundation Design", "Frontend Development", "Game Design", "Garment Construction", "Genetics", "Geological and Site Investigation", "Geological Surveys", "Geology", "Geospatial Analysis", "GIS Mapping", "Health Education", "Healthcare Management", "HR Policies", "HTML/CSS", "Human Factors Engineering", "Human-AI Interaction Design", "Incident Response", "Individualized Education Plans (IEPs)", "Information Management", "Innovation", "Instructional Strategies", "Instructional Technology", "Instrumentation", "Inventory Control", "Investment Management", "Investment Strategies", "iOS Development", "IT Infrastructure", "JavaScript", "Laboratory Techniques", "Laboratory Testing", "Language Instruction", "Leadership", "Lean Manufacturing", "Lesson Planning", "Lighting Design", "Lighting Techniques", "Load Calculations", "Load Testing", "Loan Evaluation", "Logistics Management", "Machine Learning", "Machine Learning Concepts", "Manufacturing Processes", "Marine Systems Integration", "Market Analysis", "Market Research", "Marketing Strategy", "Material Science", "Material Selection", "Materials Science", "Materials Testing", "Mathematical Modeling", "Mechanical Design", "Mechanical Systems", "Media Relations", "Medical Device Design", "Medical Imaging", "Medical Knowledge", "Medication Management", "Mental Health Support", "Mergers & Acquisitions", "Microbial Analysis", "Model Deployment", "Model Evaluation", "Model-Based Systems Engineering (MBSE)", "Molecular Biology", "Music Composition", "Natural Language Processing", "Network Configuration", "Network Security", "Neural Networks", "Node.js", "NoSQL Databases", "Nuclear Physics", "Nuclear Reactor Design", "Nutrition Planning", "Observational Techniques", "Operations Research", "Pain Management", "Pathogen Identification", "Patient Care", "Patient Counseling", "Patient Monitoring", "Pattern Making", "Penetration Testing", "Performance Optimization", "Performance Tuning", "Pharmaceutical Knowledge", "Photo Editing", "Photography", "Policy Analysis", "Policy Evaluation",
            "Policy Implementation", "Pollution Control", "Post-Production", "Power Systems", "Powertrain Engineering", "Presentation Skills", "Problem Solving", "Process Control", "Process Design", "Process Improvement", "Process Optimization", "Product Development", "Product Roadmapping", "Production Management", "Programming", "Project Management", "Project Planning", "Prompt Engineering", "Propulsion Systems", "Prototyping", "Psychological Assessment", "Public Communication", "Python", "Python/R Programming", "Quality Control", "Radiation Safety", "React", "React Native", "Reactor Design", "Recruitment", "Regression Testing", "Regulatory Compliance", "Rehabilitation", "Remediation Technologies", "Report Writing", "Requirements Engineering", "Requirements Gathering", "Research", "Research Assistance", "Research Methodologies", "Research Methodology", "Research Skills", "Reservoir Engineering", "Responsive Design", "Risk Analysis", "Risk Assessment", "Risk Management", "Roadmapping", "Robotics Design", "Rock Mechanics", "Safety Protocols", "Sales Strategy", "Scientific Computing", "Scientific Writing", "Script Analysis", "Scripting and Automation", "Security", "Security Best Practices", "Security Frameworks", "Seismic Design", "Seismic Risk Assessment", "SEO Knowledge", "Server Administration", "Server Management", "Ship Design", "Signal Processing", "Slope Stability Analysis", "Smart Contracts", "Social Engineering Techniques", "Software Architecture", "Soil and Rock Mechanics", "Sound Design", "Space Planning", "Spatial Computing", "Spinal Adjustment", "SQL", "Stakeholder Communication", "Stakeholder Engagement", "Stakeholder Management", "Statistical Analysis", "Statistical Modeling", "Statistics", "Storyboarding", "Storytelling", "Strategic Planning", "Stress Analysis", "Structural Analysis", "Structural Design", "Supplier Relations", "Supply Chain Coordination", "Supply Chain Management", "Surgical Techniques", "Sustainability", "Sustainability Reporting", "Systems Design", "Systems Integration", "Tax Compliance", "Tax Planning", "Teacher Training", "Teaching", "Team Leadership", "Technical Analysis", "Technical Documentation", "Telescope Operation", "Test Automation Frameworks", "Testing", "Testing and Debugging", "Textile Design", "Theoretical Physics", "Therapeutic Techniques", "Therapy", "Thermodynamics", "Tissue Engineering", "Transportation Management", "Trend Analysis", "Troubleshooting", "Typography", "UI/UX Design Principles", "Unit Testing", "Unity", "Unity/Unreal Engine", "User Experience Design", "User Research", "UX Design for VR/AR",
             "Vehicle Design", "Vendor Management", "Version Control", "Version Control (Git)", "Video Editing", "Vision Correction", "Visual Communication", "Visual Composition", "Visual Design", "Visual Storytelling", "VPN Setup", "Vulnerability Assessment", "Waste Management", "Water Treatment", "Weather Forecasting", "Well Design", "Wireframing", "Other"]
      },
      {
        id: 'interestedSkills',
        question: 'What skills intrigue and are you willing to learn?',
        options: ["2D/3D Animation", "3D Modeling", "Accounting", "Actor Direction", "Adaptive Teaching", "Administration", "Adobe Creative Suite", "Aerodynamics", "Agile Methodologies", "AI Fine-tuning", "AI Systems Knowledge", "Algorithms", "Anatomy", "Android Development", "Anesthesia Administration", "API Design", "API Development", "Astrophysical Research", "Atmospheric Physics", "Audio Editing", "Audio Mixing", "Auditing", "AutoCAD", "Automation", "Automotive Systems", "Avionics", "AWS", "Azure", "Backend Development", "Backup & Recovery", "Behavioral Management", "Big Data", "Big Data Tools (Spark, Hadoop)", "Bioinformatics", "Biomaterials", "Biomechanics", "Blockchain", "Brand Communication", "Brand Development", "Brand Messaging", "Budgeting", "Bug Tracking", "Building Codes and Standards", "Building Design", "Business Planning", "Business Process Modeling", "C#", "C#/C++ Programming", "CAD Design", "CAD/CAM Systems", "Carbon Footprint Analysis", "Career Guidance", "Cataloging", "Chain of Custody", "Character Design", "Chemical Analysis", "Chemical Reactions", "Child Healthcare", "CI/CD", "Cinematography", "Circuit Design", "Circular Economy Strategies", "Classroom Management", "Client Communication", "Client Management", "Client Relations", "Climate Modeling", "Clinical Evaluation", "Cloud Computing", "Color Theory", "Communication", "Communication and Presentation", "Compliance", "Computational Fluid Dynamics (CFD)", "Computational Modeling", "Computer Vision", "Computer-Aided Design (CAD)", "Conceptual Thinking", "Content Creation", "Content Writing", "Control Systems", "Counseling", "Courtroom Testimony", "Creative Direction", "Creative Strategy", "Creative Writing", "Creativity", "Credit Risk Assessment", "Crime Scene Analysis", "Crisis Management", "Critical Thinking", "CRM Management", "Cross-Browser Compatibility", "Cross-Functional Collaboration", "Cryptography", "Cultural Sensitivity", "Curriculum Design", "Curriculum Development", "Customer Relations", "Data Analysis", "Data Annotation", "Data Interpretation", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization", "Data-Driven Decision Making", "Database Management", "DAW Proficiency", "Debugging", "Decision Making", "Deep Learning", "Dental Procedures", "Diagnosis", "Dietary Counseling", "Digital Design Tools", "DNA Analysis", "Drilling Techniques", "E-Learning Development", "Editing", "Educational Research", "Electric Vehicle Technology", "Electronics", "Emergency Alert Systems", "Employee Relations", "Energy Production",
           "Enhanced Oil Recovery", "Environmental Data Analysis", "Environmental Impact Assessment", "Environmental Modeling", "Environmental Policy", "ERP System Proficiency", "Ethical Hacking", "Event Coordination", "Evidence Interpretation", "Excel", "Experimental Design", "Eye Exams", "Failure Analysis", "Fashion Illustration", "Feature Engineering", "Field Research Techniques", "Field Sampling", "Fieldwork", "Financial Analysis", "Financial Management", "Financial Modeling", "Financial Planning", "Financial Reporting", "Firewall Management", "Fluid Dynamics", "Forecasting", "Foundation Design", "Frontend Development", "Game Design", "Garment Construction", "Genetics", "Geological and Site Investigation", "Geological Surveys", "Geology", "Geospatial Analysis", "GIS Mapping", "Health Education", "Healthcare Management", "HR Policies", "HTML/CSS", "Human Factors Engineering", "Human-AI Interaction Design", "Incident Response", "Individualized Education Plans (IEPs)", "Information Management", "Innovation", "Instructional Strategies", "Instructional Technology", "Instrumentation", "Inventory Control", "Investment Management", "Investment Strategies", "iOS Development", "IT Infrastructure", "JavaScript", "Laboratory Techniques", "Laboratory Testing", "Language Instruction", "Leadership", "Lean Manufacturing", "Lesson Planning", "Lighting Design", "Lighting Techniques", "Load Calculations", "Load Testing", "Loan Evaluation", "Logistics Management", "Machine Learning", "Machine Learning Concepts", "Manufacturing Processes", "Marine Systems Integration", "Market Analysis", "Market Research", "Marketing Strategy", "Material Science", "Material Selection", "Materials Science", "Materials Testing", "Mathematical Modeling", "Mechanical Design", "Mechanical Systems", "Media Relations", "Medical Device Design", "Medical Imaging", "Medical Knowledge", "Medication Management", "Mental Health Support", "Mergers & Acquisitions", "Microbial Analysis", "Model Deployment", "Model Evaluation", "Model-Based Systems Engineering (MBSE)", "Molecular Biology", "Music Composition", "Natural Language Processing", "Network Configuration", "Network Security", "Neural Networks", "Node.js", "NoSQL Databases", "Nuclear Physics", "Nuclear Reactor Design", "Nutrition Planning", "Observational Techniques", "Operations Research", "Pain Management", "Pathogen Identification", "Patient Care", "Patient Counseling", "Patient Monitoring", "Pattern Making", "Penetration Testing", "Performance Optimization", "Performance Tuning", "Pharmaceutical Knowledge", "Photo Editing", "Photography", "Policy Analysis", "Policy Evaluation",
            "Policy Implementation", "Pollution Control", "Post-Production", "Power Systems", "Powertrain Engineering", "Presentation Skills", "Problem Solving", "Process Control", "Process Design", "Process Improvement", "Process Optimization", "Product Development", "Product Roadmapping", "Production Management", "Programming", "Project Management", "Project Planning", "Prompt Engineering", "Propulsion Systems", "Prototyping", "Psychological Assessment", "Public Communication", "Python", "Python/R Programming", "Quality Control", "Radiation Safety", "React", "React Native", "Reactor Design", "Recruitment", "Regression Testing", "Regulatory Compliance", "Rehabilitation", "Remediation Technologies", "Report Writing", "Requirements Engineering", "Requirements Gathering", "Research", "Research Assistance", "Research Methodologies", "Research Methodology", "Research Skills", "Reservoir Engineering", "Responsive Design", "Risk Analysis", "Risk Assessment", "Risk Management", "Roadmapping", "Robotics Design", "Rock Mechanics", "Safety Protocols", "Sales Strategy", "Scientific Computing", "Scientific Writing", "Script Analysis", "Scripting and Automation", "Security", "Security Best Practices", "Security Frameworks", "Seismic Design", "Seismic Risk Assessment", "SEO Knowledge", "Server Administration", "Server Management", "Ship Design", "Signal Processing", "Slope Stability Analysis", "Smart Contracts", "Social Engineering Techniques", "Software Architecture", "Soil and Rock Mechanics", "Sound Design", "Space Planning", "Spatial Computing", "Spinal Adjustment", "SQL", "Stakeholder Communication", "Stakeholder Engagement", "Stakeholder Management", "Statistical Analysis", "Statistical Modeling", "Statistics", "Storyboarding", "Storytelling", "Strategic Planning", "Stress Analysis", "Structural Analysis", "Structural Design", "Supplier Relations", "Supply Chain Coordination", "Supply Chain Management", "Surgical Techniques", "Sustainability", "Sustainability Reporting", "Systems Design", "Systems Integration", "Tax Compliance", "Tax Planning", "Teacher Training", "Teaching", "Team Leadership", "Technical Analysis", "Technical Documentation", "Telescope Operation", "Test Automation Frameworks", "Testing", "Testing and Debugging", "Textile Design", "Theoretical Physics", "Therapeutic Techniques", "Therapy", "Thermodynamics", "Tissue Engineering", "Transportation Management", "Trend Analysis", "Troubleshooting", "Typography", "UI/UX Design Principles", "Unit Testing", "Unity", "Unity/Unreal Engine", "User Experience Design", "User Research", "UX Design for VR/AR",
             "Vehicle Design", "Vendor Management", "Version Control", "Version Control (Git)", "Video Editing", "Vision Correction", "Visual Communication", "Visual Composition", "Visual Design", "Visual Storytelling", "VPN Setup", "Vulnerability Assessment", "Waste Management", "Water Treatment", "Weather Forecasting", "Well Design", "Wireframing", "Other"]
      },
      {
        id: 'mainInterests',
        question: 'What are your main interests?',
        options: ["3D Graphics", "Accounting", "AI", "Animation", "App Development", "Architecture", "Art", "Artificial Intelligence", "Astronomy", "Attention to Detail", "Augmented Reality", "Automated Systems", "Automotive", "Aviation", "Banking", "Biology", "Biotechnology", "Blockchain", "Brand Development", "Building Scalable Systems", "Business", "Business Analysis", "Business Development", "Business Innovation", "Business Intelligence", "Business Operations", "Business Strategy", "Chemistry", "Civil Engineering", "Climate", "Climate Action", "Climate Change", "Cloud Databases", "Cloud Infrastructure", "Coding", "Cognitive Science", "Collaboration", "Collaborative Work", "Communication", "Conservation", "Construction", "Consumer Behavior", "Consumer Trends", "Content Creation", "Continuous Learning", "Corporate Responsibility", "Cosmology", "Creative Writing", "Creativity", "Criminal Justice", "Cross-Functional Leadership", "Cultural Exchange", "Cultural Movements", "Cultural Trends", "Current Events", "Cybersecurity", "Data", "Data Analysis", "Data Analytics", "Data Architecture", "Data Visualization", "Data-Driven Decision Making", "Dentistry", "Design", "Digital Art", "Digital Forensics", "Earth Science", "Earth Systems", "Economics", "Education", "Efficiency", "Electricity",
          "Emerging Technologies", "Energy", "Engineering", "Enterprise Systems", "Entrepreneurship", "Environmental Conservation", "Environmental Impact", "Environmental Issues", "Environmental Protection", "Environmental Science", "Environmental Sustainability", "Ethical Hacking", "Event Management", "Experimentation", "Fashion", "Field Operations", "Film", "Finance", "Forensics", "Game Development", "Gaming", "Geology", "Global Trade", "Green Technology", "Healthcare", "Home Furnishings", "Hospitality", "Human Behavior", "Human Physiology", "Human-Computer Interaction", "Immersive Technology", "Industry Trends", "Infectious Diseases", "Information Technology", "Infrastructure", "Infrastructure Design", "Innovation", "Innovation in AI", "Insurance", "Investments", "IT Consultancy", "Laboratory Work", "Language", "Language Models", "Leadership", "Legal Processes", "Management", "Manufacturing", "Maritime Technology", "Marketing", "Marketing Strategy", "Material Science", "Materials Science", "Mathematics", "Mechanical Systems", "Mechatronics", "Medical Research", "Medicine", "Mental Health", "Mentorship", "Meteorology", "Microbiology", "Mobile Apps", "Music", "Natural Resources", "Nature", "Naval Innovation", "Negotiation", "Networking", "New Materials", "Nuclear Science", "Numbers", "Nutrition", "Operations", "Organization", "Organizational Behavior", "Organizational Development", "Outdoor Work", "Pediatrics", "People Skills", "Physical Therapy", "Physics", "Policy", "Popular Culture", "Power Generation",
          "Predictive Analytics", "Privacy Protection", "Problem Solving", "Process Improvement", "Product Innovation", "Psychology", "Public Health", "Public Policy", "Public Relations", "Public Safety", "Quality Assurance", "Rehabilitation", "Renewable Energy", "Research", "Research and Development", "Risk Management", "Robotics", "Safety Systems", "Sales", "Science", "Software Development", "Software Quality Advocacy", "Sound Engineering", "Space", "Space Exploration", "Special Needs", "Startups", "Statistics", "Storytelling", "Surgery", "Sustainability", "Sustainable Building", "Sustainable Extraction", "Systems Optimization", "Systems Thinking", "Taxation", "Teaching", "Team Collaboration", "Technology", "Technology Implementation", "Technology Management", "Textiles", "Transportation", "User Experience", "User-Centered Testing", "User-Centric Design", "User-Centric Innovation", "Virtual Reality", "Vision Care", "Visual Arts", "Visual Culture", "Visual Storytelling", "Wealth Management", "Wellness", "Writing", "Other"]
      },
      {
        id: 'interestedFields',
        question: 'What fields are you interested in?',
        options: ["Technology", "Business", "Healthcare", "Finance", "Creative Arts",
    "Engineering", "Science", "Education", "Environment", 'Other']
      },
      {
        id: 'careerGoals',
        question: 'What are your goals for your career growth?',
        options: ['Move to Management', 'Become Subject Matter Expert', 'Start Own Business', 'Switch Industries', 'Work Internationally', 'Achieve Work-Life Balance', 'Other']
      }
    ],
    "Horizon Changer": [
      {
        id: 'currentPath',
        question: 'What career path are you currently in?',
        options: ["Accountant", "Actuary", "Aerospace Engineer", "AI Engineer", "AI Product Manager", "Anesthesiologist", "Animator", "Art Director", "Astronomer", "Auditor", "Automotive Engineer", "Backend Developer", "Biologist", "Biomedical Engineer", "Biotechnologist", "Blockchain Developer", "Business Analyst", "Chemical Engineer", "Chemist", "Chiropractor", "Civil Engineer", "Climate Scientist", 
    "Cloud Architect", "College Professor", "Copywriter", "Creative Director", "Credit Analyst", "Curriculum Developer", "Cybersecurity Analyst", "Data Analyst", "Data Engineer", "Data Scientist", "Database Administrator", "Dentist", "DevOps Engineer", "Dietitian", "Education Policy Analyst", "Educational Consultant", "Electrical Engineer", "Entrepreneur", "Environmental Engineer", "Environmental Scientist", "ESL Teacher", "Ethical Hacker", "Event Planner", "Fashion Designer", "Film Director", "Financial Analyst", "Financial Planner", "Forensic Scientist", "Frontend Developer", "Full-Stack Developer", "Game Developer", "Geologist", "Geotechnical Engineer", "Graphic Designer", "Healthcare Administrator", "Human Resources Manager", "Industrial Engineer", "Instructional Designer", "Insurance Underwriter", "Interior Designer", "Investment Banker", "IT Manager", "Librarian", "Logistics Manager", "Machine Learning Engineer", "Management Consultant", "Marine Engineer", "Materials Engineer", "Mechanical Engineer", "Medical Laboratory Scientist", "Medical Researcher", "Meteorologist", "Microbiologist", "Mobile App Developer", "Music Producer", "Network Administrator", "Nuclear Engineer", "Nurse Practitioner", "Occupational Therapist", "Operations Manager", "Optometrist", "Pediatrician", "Petroleum Engineer", "Pharmacist", "Photographer", "Physical Therapist", "Physicist", "Product Manager", "Project Manager", "Prompt Engineer", "Psychologist", "Public Relations Manager", "QA Engineer", "Radiologist", "Risk Manager", 
    "Robotics Engineer", "Sales Manager", "School Counselor", "School Principal", "Software Engineer", "Special Education Teacher", "Structural Engineer", "Supply Chain Manager", "Surgeon", "Sustainability Specialist", "Systems Analyst", "Systems Engineer", "Tax Consultant", "Teacher", "Technical Writer", "UX Designer", "Video Editor", "VR/AR Developer", "Wealth Manager"]
      },
      {
        id: 'yearsExperience',
        question: 'How many years of experience do you have in that path?',
        options: ['2-5 years', '6-10 years', '11-15 years', '16-20 years', '20+ years']
      },
      {
        id: 'seniorityLevel',
        question: 'What is your seniority level?',
        options: ['Mid-level', 'Senior', 'Lead/Manager', 'Director', 'VP/Executive', 'C-Suite']
      },
      {
        id: 'educationLevel',
        question: 'What level of education have you attained?',
        options: ['High School', 'Some College', 'Associate Degree', 'Bachelor\'s Degree', 'Master\'s Degree', 'PhD']
      },
      {
        id: 'program',
        question: 'What program?',
        options: ["Other (please specify)","Accounting", "Actuarial Science", "Advertising", "Aerospace Engineering", "Anesthesiology", "Animation", "Applied Mathematics", "Applied Physics", "Architectural Engineering", "Architecture", "Artificial Intelligence", "Astronautical Engineering", "Astronomy", "Astrophysics", "Atmospheric Science", "Atmospheric Sciences", "Audio Technology", "Automotive Engineering", "Avionics Engineering", "Biochemical Engineering", "Biochemistry", "Biology", "Biomechanical Engineering",
    "Biomedical Engineering", "Biomedical Science", "Biotechnology", "Business Administration", "Business Analytics", "Business Technology", "Chemical Engineering", "Chemistry", "Chiropractic Medicine", "Cinematography", "Civil Engineering", "Climate Policy", "Climate Science", "Clinical Psychology", "Cognitive Science", "Communications", "Computational Astrophysics", "Computer Engineering", "Computer Graphics", "Computer Science", "Computer Science with Robotics focus", "Conservation Biology", "Construction Engineering", "Corporate Sustainability", "Counseling",
    "Criminal Justice", "Cryptography", "Curriculum and Instruction", "Cybersecurity", "Data Engineering", "Data Science", "Dentistry", "Dietetics", "Digital Arts", "Digital Media", "Directing", "Earth Science", "Ecological Engineering", "Ecology", "Economics", "Education", "Education Administration", "Education Policy", "Educational Leadership", "Educational Technology", "Electrical Engineering", "Engineering Geology", "Engineering Management", "Engineering Physics", "English", "Entrepreneurship", "Environmental Design", "Environmental Engineering", "Environmental Geology", "Environmental Science", "Event Management", "Fashion Design", "Fashion Merchandising", "Fashion Technology", "Film Production", "Film Studies", "Finance", "Financial Technology",
    "Fine Arts", "Forensic Science", "Game Development", "Geological Engineering", "Geology", "Geophysics",
    "Geosciences", "Geotechnical Engineering", "Graphic Design", "Healthcare Administration", "Hospitality Management", "Human Resources",
    "Human-Computer Interaction", "Immunology", "Industrial Engineering", "Information Assurance", "Information Science", "Information Security",
    "Information Systems", "Information Technology", "Innovation Management", "Instructional Design", "Interactive Media",
    "Interior Architecture", "Interior Design", "Journalism", "Library Science", "Linguistics", "Logistics Management", "Machine Learning", "Management", "Management Information Systems", "Manufacturing Engineering", "Marine Biology", "Marine Engineering", "Marketing", "Materials Engineering", "Materials Science", "Mathematics", "Mechanical Engineering", "Mechanical Engineering with Nuclear focus", "Mechanical Engineering with Petroleum focus", "Mechatronics", "Media Arts", "Media Studies", "Medical Engineering", "Medical Laboratory Science", "Medical Microbiology", "Medicine", "Metallurgical Engineering", "Meteorology", "Microbiology", "Molecular Biology", "Molecular Genetics", "Music Business", "Music Production", "Naval Architecture", "Network Engineering", "Network Security", "Nuclear Engineering", "Nursing", "Nutrition",
    "Occupational Therapy", "Ocean Engineering", "Oceanography", "Operations Management", "Optometry", "Pediatrics", "Petroleum Engineering", "Pharmacy", "Photography", "Physical Therapy", "Physics", "Process Engineering", "Project Management", "Psychology", "Public Health", "Public Policy", "Public Relations", "Radiological Science", "Radiology", "Risk Management",
    "Robotics Engineering", "Software Architecture", "Software Engineering", "Sound Engineering", "Space Science", "Special Education", "Statistics", "Structural Engineering", "Subject-Specific Degree", "Supply Chain Management", "Surgery", "Sustainability Management", "Systems Engineering", "Taxation", "Technical Communication", "Textile Design", "Visual Arts", "Visual Communications", "Web Development"],
        conditional: (answers: Record<string, any>) => {
          const educationLevel = answers.educationLevel;
          return educationLevel && !['High School', 'Some College'].includes(educationLevel);
        }
      },
      {
        id: 'mainInterests',
        question: 'What are your main interests?',
        options: ["3D Graphics", "Accounting", "AI", "Animation", "App Development", "Architecture", "Art", "Artificial Intelligence", "Astronomy", "Attention to Detail", "Augmented Reality", "Automated Systems", "Automotive", "Aviation", "Banking", "Biology", "Biotechnology", "Blockchain", "Brand Development", "Building Scalable Systems", "Business", "Business Analysis", "Business Development", "Business Innovation", "Business Intelligence", "Business Operations", "Business Strategy", "Chemistry", "Civil Engineering", "Climate", "Climate Action", "Climate Change", "Cloud Databases", "Cloud Infrastructure", "Coding", "Cognitive Science", "Collaboration", "Collaborative Work", "Communication", "Conservation", "Construction", "Consumer Behavior", "Consumer Trends", "Content Creation", "Continuous Learning", "Corporate Responsibility", "Cosmology", "Creative Writing", "Creativity", "Criminal Justice", "Cross-Functional Leadership", "Cultural Exchange", "Cultural Movements", "Cultural Trends", "Current Events", "Cybersecurity", "Data", "Data Analysis", "Data Analytics", "Data Architecture", "Data Visualization", "Data-Driven Decision Making", "Dentistry", "Design", "Digital Art", "Digital Forensics", "Earth Science", "Earth Systems", "Economics", "Education", "Efficiency", "Electricity",
          "Emerging Technologies", "Energy", "Engineering", "Enterprise Systems", "Entrepreneurship", "Environmental Conservation", "Environmental Impact", "Environmental Issues", "Environmental Protection", "Environmental Science", "Environmental Sustainability", "Ethical Hacking", "Event Management", "Experimentation", "Fashion", "Field Operations", "Film", "Finance", "Forensics", "Game Development", "Gaming", "Geology", "Global Trade", "Green Technology", "Healthcare", "Home Furnishings", "Hospitality", "Human Behavior", "Human Physiology", "Human-Computer Interaction", "Immersive Technology", "Industry Trends", "Infectious Diseases", "Information Technology", "Infrastructure", "Infrastructure Design", "Innovation", "Innovation in AI", "Insurance", "Investments", "IT Consultancy", "Laboratory Work", "Language", "Language Models", "Leadership", "Legal Processes", "Management", "Manufacturing", "Maritime Technology", "Marketing", "Marketing Strategy", "Material Science", "Materials Science", "Mathematics", "Mechanical Systems", "Mechatronics", "Medical Research", "Medicine", "Mental Health", "Mentorship", "Meteorology", "Microbiology", "Mobile Apps", "Music", "Natural Resources", "Nature", "Naval Innovation", "Negotiation", "Networking", "New Materials", "Nuclear Science", "Numbers", "Nutrition", "Operations", "Organization", "Organizational Behavior", "Organizational Development", "Outdoor Work", "Pediatrics", "People Skills", "Physical Therapy", "Physics", "Policy", "Popular Culture", "Power Generation",
          "Predictive Analytics", "Privacy Protection", "Problem Solving", "Process Improvement", "Product Innovation", "Psychology", "Public Health", "Public Policy", "Public Relations", "Public Safety", "Quality Assurance", "Rehabilitation", "Renewable Energy", "Research", "Research and Development", "Risk Management", "Robotics", "Safety Systems", "Sales", "Science", "Software Development", "Software Quality Advocacy", "Sound Engineering", "Space", "Space Exploration", "Special Needs", "Startups", "Statistics", "Storytelling", "Surgery", "Sustainability", "Sustainable Building", "Sustainable Extraction", "Systems Optimization", "Systems Thinking", "Taxation", "Teaching", "Team Collaboration", "Technology", "Technology Implementation", "Technology Management", "Textiles", "Transportation", "User Experience", "User-Centered Testing", "User-Centric Design", "User-Centric Innovation", "Virtual Reality", "Vision Care", "Visual Arts", "Visual Culture", "Visual Storytelling", "Wealth Management", "Wellness", "Writing", "Other"]
      },
      {
        id: 'interestedFields',
        question: 'What fields are you interested in?',
        options: ["Technology", "Business", "Healthcare", "Finance", "Creative Arts",
    "Engineering", "Science", "Education", "Environment", 'Other']
      },
      {
        id: 'currentSkills',
        question: 'What skills do you possess?',
        options: ["2D/3D Animation", "3D Modeling", "Accounting", "Actor Direction", "Adaptive Teaching", "Administration", "Adobe Creative Suite", "Aerodynamics", "Agile Methodologies", "AI Fine-tuning", "AI Systems Knowledge", "Algorithms", "Anatomy", "Android Development", "Anesthesia Administration", "API Design", "API Development", "Astrophysical Research", "Atmospheric Physics", "Audio Editing", "Audio Mixing", "Auditing", "AutoCAD", "Automation", "Automotive Systems", "Avionics", "AWS", "Azure", "Backend Development", "Backup & Recovery", "Behavioral Management", "Big Data", "Big Data Tools (Spark, Hadoop)", "Bioinformatics", "Biomaterials", "Biomechanics", "Blockchain", "Brand Communication", "Brand Development", "Brand Messaging", "Budgeting", "Bug Tracking", "Building Codes and Standards", "Building Design", "Business Planning", "Business Process Modeling", "C#", "C#/C++ Programming", "CAD Design", "CAD/CAM Systems", "Carbon Footprint Analysis", "Career Guidance", "Cataloging", "Chain of Custody", "Character Design", "Chemical Analysis", "Chemical Reactions", "Child Healthcare", "CI/CD", "Cinematography", "Circuit Design", "Circular Economy Strategies", "Classroom Management", "Client Communication", "Client Management", "Client Relations", "Climate Modeling", "Clinical Evaluation", "Cloud Computing", "Color Theory", "Communication", "Communication and Presentation", "Compliance", "Computational Fluid Dynamics (CFD)", "Computational Modeling", "Computer Vision", "Computer-Aided Design (CAD)", "Conceptual Thinking", "Content Creation", "Content Writing", "Control Systems", "Counseling", "Courtroom Testimony", "Creative Direction", "Creative Strategy", "Creative Writing", "Creativity", "Credit Risk Assessment", "Crime Scene Analysis", "Crisis Management", "Critical Thinking", "CRM Management", "Cross-Browser Compatibility", "Cross-Functional Collaboration", "Cryptography", "Cultural Sensitivity", "Curriculum Design", "Curriculum Development", "Customer Relations", "Data Analysis", "Data Annotation", "Data Interpretation", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization", "Data-Driven Decision Making", "Database Management", "DAW Proficiency", "Debugging", "Decision Making", "Deep Learning", "Dental Procedures", "Diagnosis", "Dietary Counseling", "Digital Design Tools", "DNA Analysis", "Drilling Techniques", "E-Learning Development", "Editing", "Educational Research", "Electric Vehicle Technology", "Electronics", "Emergency Alert Systems", "Employee Relations", "Energy Production",
           "Enhanced Oil Recovery", "Environmental Data Analysis", "Environmental Impact Assessment", "Environmental Modeling", "Environmental Policy", "ERP System Proficiency", "Ethical Hacking", "Event Coordination", "Evidence Interpretation", "Excel", "Experimental Design", "Eye Exams", "Failure Analysis", "Fashion Illustration", "Feature Engineering", "Field Research Techniques", "Field Sampling", "Fieldwork", "Financial Analysis", "Financial Management", "Financial Modeling", "Financial Planning", "Financial Reporting", "Firewall Management", "Fluid Dynamics", "Forecasting", "Foundation Design", "Frontend Development", "Game Design", "Garment Construction", "Genetics", "Geological and Site Investigation", "Geological Surveys", "Geology", "Geospatial Analysis", "GIS Mapping", "Health Education", "Healthcare Management", "HR Policies", "HTML/CSS", "Human Factors Engineering", "Human-AI Interaction Design", "Incident Response", "Individualized Education Plans (IEPs)", "Information Management", "Innovation", "Instructional Strategies", "Instructional Technology", "Instrumentation", "Inventory Control", "Investment Management", "Investment Strategies", "iOS Development", "IT Infrastructure", "JavaScript", "Laboratory Techniques", "Laboratory Testing", "Language Instruction", "Leadership", "Lean Manufacturing", "Lesson Planning", "Lighting Design", "Lighting Techniques", "Load Calculations", "Load Testing", "Loan Evaluation", "Logistics Management", "Machine Learning", "Machine Learning Concepts", "Manufacturing Processes", "Marine Systems Integration", "Market Analysis", "Market Research", "Marketing Strategy", "Material Science", "Material Selection", "Materials Science", "Materials Testing", "Mathematical Modeling", "Mechanical Design", "Mechanical Systems", "Media Relations", "Medical Device Design", "Medical Imaging", "Medical Knowledge", "Medication Management", "Mental Health Support", "Mergers & Acquisitions", "Microbial Analysis", "Model Deployment", "Model Evaluation", "Model-Based Systems Engineering (MBSE)", "Molecular Biology", "Music Composition", "Natural Language Processing", "Network Configuration", "Network Security", "Neural Networks", "Node.js", "NoSQL Databases", "Nuclear Physics", "Nuclear Reactor Design", "Nutrition Planning", "Observational Techniques", "Operations Research", "Pain Management", "Pathogen Identification", "Patient Care", "Patient Counseling", "Patient Monitoring", "Pattern Making", "Penetration Testing", "Performance Optimization", "Performance Tuning", "Pharmaceutical Knowledge", "Photo Editing", "Photography", "Policy Analysis", "Policy Evaluation",
            "Policy Implementation", "Pollution Control", "Post-Production", "Power Systems", "Powertrain Engineering", "Presentation Skills", "Problem Solving", "Process Control", "Process Design", "Process Improvement", "Process Optimization", "Product Development", "Product Roadmapping", "Production Management", "Programming", "Project Management", "Project Planning", "Prompt Engineering", "Propulsion Systems", "Prototyping", "Psychological Assessment", "Public Communication", "Python", "Python/R Programming", "Quality Control", "Radiation Safety", "React", "React Native", "Reactor Design", "Recruitment", "Regression Testing", "Regulatory Compliance", "Rehabilitation", "Remediation Technologies", "Report Writing", "Requirements Engineering", "Requirements Gathering", "Research", "Research Assistance", "Research Methodologies", "Research Methodology", "Research Skills", "Reservoir Engineering", "Responsive Design", "Risk Analysis", "Risk Assessment", "Risk Management", "Roadmapping", "Robotics Design", "Rock Mechanics", "Safety Protocols", "Sales Strategy", "Scientific Computing", "Scientific Writing", "Script Analysis", "Scripting and Automation", "Security", "Security Best Practices", "Security Frameworks", "Seismic Design", "Seismic Risk Assessment", "SEO Knowledge", "Server Administration", "Server Management", "Ship Design", "Signal Processing", "Slope Stability Analysis", "Smart Contracts", "Social Engineering Techniques", "Software Architecture", "Soil and Rock Mechanics", "Sound Design", "Space Planning", "Spatial Computing", "Spinal Adjustment", "SQL", "Stakeholder Communication", "Stakeholder Engagement", "Stakeholder Management", "Statistical Analysis", "Statistical Modeling", "Statistics", "Storyboarding", "Storytelling", "Strategic Planning", "Stress Analysis", "Structural Analysis", "Structural Design", "Supplier Relations", "Supply Chain Coordination", "Supply Chain Management", "Surgical Techniques", "Sustainability", "Sustainability Reporting", "Systems Design", "Systems Integration", "Tax Compliance", "Tax Planning", "Teacher Training", "Teaching", "Team Leadership", "Technical Analysis", "Technical Documentation", "Telescope Operation", "Test Automation Frameworks", "Testing", "Testing and Debugging", "Textile Design", "Theoretical Physics", "Therapeutic Techniques", "Therapy", "Thermodynamics", "Tissue Engineering", "Transportation Management", "Trend Analysis", "Troubleshooting", "Typography", "UI/UX Design Principles", "Unit Testing", "Unity", "Unity/Unreal Engine", "User Experience Design", "User Research", "UX Design for VR/AR",
             "Vehicle Design", "Vendor Management", "Version Control", "Version Control (Git)", "Video Editing", "Vision Correction", "Visual Communication", "Visual Composition", "Visual Design", "Visual Storytelling", "VPN Setup", "Vulnerability Assessment", "Waste Management", "Water Treatment", "Weather Forecasting", "Well Design", "Wireframing", "Other"]
      },
      {
        id: 'interestedSkills',
        question: 'What skills intrigue and are you willing to learn?',
        options: ["2D/3D Animation", "3D Modeling", "Accounting", "Actor Direction", "Adaptive Teaching", "Administration", "Adobe Creative Suite", "Aerodynamics", "Agile Methodologies", "AI Fine-tuning", "AI Systems Knowledge", "Algorithms", "Anatomy", "Android Development", "Anesthesia Administration", "API Design", "API Development", "Astrophysical Research", "Atmospheric Physics", "Audio Editing", "Audio Mixing", "Auditing", "AutoCAD", "Automation", "Automotive Systems", "Avionics", "AWS", "Azure", "Backend Development", "Backup & Recovery", "Behavioral Management", "Big Data", "Big Data Tools (Spark, Hadoop)", "Bioinformatics", "Biomaterials", "Biomechanics", "Blockchain", "Brand Communication", "Brand Development", "Brand Messaging", "Budgeting", "Bug Tracking", "Building Codes and Standards", "Building Design", "Business Planning", "Business Process Modeling", "C#", "C#/C++ Programming", "CAD Design", "CAD/CAM Systems", "Carbon Footprint Analysis", "Career Guidance", "Cataloging", "Chain of Custody", "Character Design", "Chemical Analysis", "Chemical Reactions", "Child Healthcare", "CI/CD", "Cinematography", "Circuit Design", "Circular Economy Strategies", "Classroom Management", "Client Communication", "Client Management", "Client Relations", "Climate Modeling", "Clinical Evaluation", "Cloud Computing", "Color Theory", "Communication", "Communication and Presentation", "Compliance", "Computational Fluid Dynamics (CFD)", "Computational Modeling", "Computer Vision", "Computer-Aided Design (CAD)", "Conceptual Thinking", "Content Creation", "Content Writing", "Control Systems", "Counseling", "Courtroom Testimony", "Creative Direction", "Creative Strategy", "Creative Writing", "Creativity", "Credit Risk Assessment", "Crime Scene Analysis", "Crisis Management", "Critical Thinking", "CRM Management", "Cross-Browser Compatibility", "Cross-Functional Collaboration", "Cryptography", "Cultural Sensitivity", "Curriculum Design", "Curriculum Development", "Customer Relations", "Data Analysis", "Data Annotation", "Data Interpretation", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization", "Data-Driven Decision Making", "Database Management", "DAW Proficiency", "Debugging", "Decision Making", "Deep Learning", "Dental Procedures", "Diagnosis", "Dietary Counseling", "Digital Design Tools", "DNA Analysis", "Drilling Techniques", "E-Learning Development", "Editing", "Educational Research", "Electric Vehicle Technology", "Electronics", "Emergency Alert Systems", "Employee Relations", "Energy Production",
          "Enhanced Oil Recovery", "Environmental Data Analysis", "Environmental Impact Assessment", "Environmental Modeling", "Environmental Policy", "ERP System Proficiency", "Ethical Hacking", "Event Coordination", "Evidence Interpretation", "Excel", "Experimental Design", "Eye Exams", "Failure Analysis", "Fashion Illustration", "Feature Engineering", "Field Research Techniques", "Field Sampling", "Fieldwork", "Financial Analysis", "Financial Management", "Financial Modeling", "Financial Planning", "Financial Reporting", "Firewall Management", "Fluid Dynamics", "Forecasting", "Foundation Design", "Frontend Development", "Game Design", "Garment Construction", "Genetics", "Geological and Site Investigation", "Geological Surveys", "Geology", "Geospatial Analysis", "GIS Mapping", "Health Education", "Healthcare Management", "HR Policies", "HTML/CSS", "Human Factors Engineering", "Human-AI Interaction Design", "Incident Response", "Individualized Education Plans (IEPs)", "Information Management", "Innovation", "Instructional Strategies", "Instructional Technology", "Instrumentation", "Inventory Control", "Investment Management", "Investment Strategies", "iOS Development", "IT Infrastructure", "JavaScript", "Laboratory Techniques", "Laboratory Testing", "Language Instruction", "Leadership", "Lean Manufacturing", "Lesson Planning", "Lighting Design", "Lighting Techniques", "Load Calculations", "Load Testing", "Loan Evaluation", "Logistics Management", "Machine Learning", "Machine Learning Concepts", "Manufacturing Processes", "Marine Systems Integration", "Market Analysis", "Market Research", "Marketing Strategy", "Material Science", "Material Selection", "Materials Science", "Materials Testing", "Mathematical Modeling", "Mechanical Design", "Mechanical Systems", "Media Relations", "Medical Device Design", "Medical Imaging", "Medical Knowledge", "Medication Management", "Mental Health Support", "Mergers & Acquisitions", "Microbial Analysis", "Model Deployment", "Model Evaluation", "Model-Based Systems Engineering (MBSE)", "Molecular Biology", "Music Composition", "Natural Language Processing", "Network Configuration", "Network Security", "Neural Networks", "Node.js", "NoSQL Databases", "Nuclear Physics", "Nuclear Reactor Design", "Nutrition Planning", "Observational Techniques", "Operations Research", "Pain Management", "Pathogen Identification", "Patient Care", "Patient Counseling", "Patient Monitoring", "Pattern Making", "Penetration Testing", "Performance Optimization", "Performance Tuning", "Pharmaceutical Knowledge", "Photo Editing", "Photography", "Policy Analysis", "Policy Evaluation",
          "Policy Implementation", "Pollution Control", "Post-Production", "Power Systems", "Powertrain Engineering", "Presentation Skills", "Problem Solving", "Process Control", "Process Design", "Process Improvement", "Process Optimization", "Product Development", "Product Roadmapping", "Production Management", "Programming", "Project Management", "Project Planning", "Prompt Engineering", "Propulsion Systems", "Prototyping", "Psychological Assessment", "Public Communication", "Python", "Python/R Programming", "Quality Control", "Radiation Safety", "React", "React Native", "Reactor Design", "Recruitment", "Regression Testing", "Regulatory Compliance", "Rehabilitation", "Remediation Technologies", "Report Writing", "Requirements Engineering", "Requirements Gathering", "Research", "Research Assistance", "Research Methodologies", "Research Methodology", "Research Skills", "Reservoir Engineering", "Responsive Design", "Risk Analysis", "Risk Assessment", "Risk Management", "Roadmapping", "Robotics Design", "Rock Mechanics", "Safety Protocols", "Sales Strategy", "Scientific Computing", "Scientific Writing", "Script Analysis", "Scripting and Automation", "Security", "Security Best Practices", "Security Frameworks", "Seismic Design", "Seismic Risk Assessment", "SEO Knowledge", "Server Administration", "Server Management", "Ship Design", "Signal Processing", "Slope Stability Analysis", "Smart Contracts", "Social Engineering Techniques", "Software Architecture", "Soil and Rock Mechanics", "Sound Design", "Space Planning", "Spatial Computing", "Spinal Adjustment", "SQL", "Stakeholder Communication", "Stakeholder Engagement", "Stakeholder Management", "Statistical Analysis", "Statistical Modeling", "Statistics", "Storyboarding", "Storytelling", "Strategic Planning", "Stress Analysis", "Structural Analysis", "Structural Design", "Supplier Relations", "Supply Chain Coordination", "Supply Chain Management", "Surgical Techniques", "Sustainability", "Sustainability Reporting", "Systems Design", "Systems Integration", "Tax Compliance", "Tax Planning", "Teacher Training", "Teaching", "Team Leadership", "Technical Analysis", "Technical Documentation", "Telescope Operation", "Test Automation Frameworks", "Testing", "Testing and Debugging", "Textile Design", "Theoretical Physics", "Therapeutic Techniques", "Therapy", "Thermodynamics", "Tissue Engineering", "Transportation Management", "Trend Analysis", "Troubleshooting", "Typography", "UI/UX Design Principles", "Unit Testing", "Unity", "Unity/Unreal Engine", "User Experience Design", "User Research", "UX Design for VR/AR",
          "Vehicle Design", "Vendor Management", "Version Control", "Version Control (Git)", "Video Editing", "Vision Correction", "Visual Communication", "Visual Composition", "Visual Design", "Visual Storytelling", "VPN Setup", "Vulnerability Assessment", "Waste Management", "Water Treatment", "Weather Forecasting", "Well Design", "Wireframing", "Other"]
      },
      {
        id: 'currentWorkEnvironment',
        question: 'What work environment are you in now?',
        options: ['Large Corporation', 'Mid-size Company', 'Startup', 'Government', 'Non-profit', 'Consulting Firm', 'Self-employed', 'Other']
      },
      {
        id: 'preferredWorkEnvironment',
        question: 'What work environment are you interested in in your next path?',
        options: ['Startup', 'Scale-up Company', 'Large Corporation', 'Consulting', 'Non-profit', 'Government', 'Entrepreneurship', 'Other']
      },
      {
        id: 'reasonForChange',
        question: 'Why do you want to change your path?',
        options: ['Seeking new challenges', 'Better work-life balance', 'Higher compensation', 'More meaningful work', 'Career growth opportunities', 'Industry changes', 'Personal fulfillment', 'Other'],
        allowCustom: true
      },
      {
        id: 'changeUrgency',
        question: 'How urgent is this change for you?',
        options: ['Immediately (0-3 months)', 'Soon (3-6 months)', 'Within a year', 'In 1-2 years', 'Exploring options (2+ years)']
      }
    ]
  };
  
  // Configuration arrays for question behavior
  export const multiSelectIds = [
    'currentSkills',
    'interestedSkills',
    'mainInterests',
    'interestedFields',
    'careerGoals',
    'reasonForChange'
  ];
  
  export const searchEnabledIds = [
    'program',
    'currentPath',
    'currentSkills',
    'interestedSkills',
    'mainInterests'
  ];